name: Main Pipeline
run-name: ${{ github.actor }} runs Main Pipeline
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  E2E-Tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        browser: [firefox, chromium, webkit]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - uses: insightsengineering/pip-action@v2
        with:
          packages: |
            pipenv
      - run: pip install 
      - run: echo $(ls -ls)
      - run: npm run setup
      - run: npm run start&
      - run: pipenv install
      - run: pipenv run playwright install-deps
      - run: pipenv run playwright install 
      - run: pipenv run echo $browser
      - run: pipenv run python -m unittest discover -s tests -p '*_test.py'

 
