name: Main Pipeline
run-name: ${{ github.actor }} runs Main Pipeline
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  E2E-Tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [firefox, chromium, webkit]
    steps:
      - run: npm run setup
      - run: npm run start&
      - run: pipenv install
      - run: pipenv run playwright install-deps
      - run: pipenv run playwright install 
      - run: pipenv run echo $browser
      - run: pipenv run python -m unittest discover -s tests -p '*_test.py'

 
