name: Main Pipeline
run-name: ${{ github.actor }} runs Main Pipeline
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Building would happen here. Generating some artifact, which will be passed to the subsequent jobs"
  E2E-Tests:
    needs: Build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        browser: [firefox, chromium, webkit]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install pipenv
        uses: insightsengineering/pip-action@v2
        with:
          packages: |
            pipenv
      - name: Setup application
        run: npm run setup
      - name: Start webserver
        run: npm run start&
      - name: Setting up python environment via pipenv
        run: pipenv install
      - name: Installing playwright dependencies
        run: pipenv run playwright install-deps
      - name: Installing playwright
        run: pipenv run playwright install 
      - name: Creating debugs-artificat directory
        run: mkdir -p debugs
      - name: Running E2E tests
        run: pipenv run python -m unittest discover -s tests_e2e -p '*_test.py'
      - uses: actions/upload-artifact@v4
        with:
          name: debugs${{ github.job }}-${{ matrix.browser }}
          path: debugs/

